# Generated by Django 4.2.3 on 2023-07-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Garçom', 'Garçom'), ('Cozinheiro', 'Cozinheiro'), ('Atendente', 'Atendente'), ('Gerente', 'Gerente'), ('Outro', 'Outro')], max_length=20)),
                ('data_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Prato Principal', 'Prato Principal'), ('Sobremesa', 'Sobremesa'), ('Bebida', 'Bebida')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
