# Generated by Django 4.2.3 on 2023-07-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
