# Generated by Django 4.2.3 on 2023-07-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='restaurante',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
