# Generated by Django 4.2.3 on 2023-07-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customuser_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='CustomUser',
        ),
    ]
