# Generated by Django 4.2.3 on 2023-07-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_principal', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Pedido',
        ),
    ]
