# Generated by Django 4.2.3 on 2023-07-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
