# Generated by Django 4.2.3 on 2023-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback_app', '0006_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Bom'), (3, 'Regular'), (2, 'Ruim'), (1, 'Péssimo')])),
            ],
        ),
    ]
